name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.arshiya@2207 }}" | docker login -u "${{ secrets.arshiya2207 }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t arshiya2207/flaskapp:latest .

    - name: Push to Docker Hub
      run: docker push arshiya2207/flaskapp:latest
